/** HTML site haritası ve iç link tutarlılığı için statik rotalar (filtre/arama sayfası yok). */
export const SITE_HTML_SITEMAP_LINKS: { path: string; label: string }[] = [
  { path: '/', label: 'Canlı Altın Fiyatları' },
  { path: '/gram-altin-nedir', label: 'Gram Altın Nedir?' },
  { path: '/ceyrek-altin-fiyati', label: 'Çeyrek Altın Fiyatı' },
  { path: '/yarim-altin-fiyati', label: 'Yarım Altın Fiyatı' },
  { path: '/tam-altin-fiyati', label: 'Tam Altın Fiyatı' },
  { path: '/cumhuriyet-altini-fiyati', label: 'Cumhuriyet Altını Fiyatı' },
  { path: '/ons-altin-fiyati', label: 'Ons Altın Fiyatı' },
  { path: '/22-ayar-bilezik-fiyati', label: '22 Ayar Bilezik Fiyatı' },
  { path: '/gram-altin-fiyatlari-dizin', label: '1–100 Gram Altın Fiyatları (dizin)' },
  { path: '/altin-nasil-alinir', label: 'Altın Nasıl Alınır?' },
  { path: '/altin-yatirim-rehberi', label: 'Altın Yatırım Rehberi' },
  { path: '/altin-cesitleri', label: 'Altın Çeşitleri' },
  { path: '/doviz-kurlari', label: 'Döviz Kurları' },
  { path: '/kapalicarsi-altin-fiyatlari', label: 'Kapalıçarşı Altın Fiyatları' },
  { path: '/harem-altin', label: 'Harem Altın' },
  { path: '/gram-altin-hesaplama', label: 'Gram Altın Hesaplama' },
  { path: '/altin-fiyatlari-istanbul', label: 'İstanbul Altın Fiyatları' },
  { path: '/altin-fiyatlari-ankara', label: 'Ankara Altın Fiyatları' },
  { path: '/altin-fiyatlari-izmir', label: 'İzmir Altın Fiyatları' },
  { path: '/altin-fiyatlari-antalya', label: 'Antalya Altın Fiyatları' },
  { path: '/altin-fiyatlari-bursa', label: 'Bursa Altın Fiyatları' },
  { path: '/altin-fiyatlari-diyarbakir', label: 'Diyarbakır Altın Fiyatları' },
  { path: '/altin-fiyatlari-gaziantep', label: 'Gaziantep Altın Fiyatları' },
  { path: '/altin-fiyatlari-adana', label: 'Adana Altın Fiyatları' },
  { path: '/altin-fiyatlari-batman', label: 'Batman Altın Fiyatları' },
  { path: '/blog', label: 'Altın Blog' },
  { path: '/site-haritasi', label: 'HTML Site Haritası' },
];
